<?php require __DIR__ . '/includes/bootstrap.php';
page_start('Cookie Policy | Atelier Doria','Informazioni su cookie, memoria locale e servizi di terze parti del sito Atelier Doria.'); ?>
<header class="page-hero legal-hero"><div><p class="eyebrow">Trasparenza</p><h1>Cookie Policy</h1><p>Informazioni sui dati memorizzati nel browser e sui contenuti di terze parti.</p></div></header>
<article class="section legal-page">
  <p class="legal-updated"><strong>Ultimo aggiornamento:</strong> 6 agosto 2026. <strong>Bozza soggetta a verifica legale prima della pubblicazione definitiva.</strong></p>
  <section><h2>1. Cosa sono cookie e strumenti simili</h2><p>I cookie sono piccoli file di testo salvati dal browser. Tecnologie come localStorage e sessionStorage possono conservare informazioni sul dispositivo con modalità analoghe.</p></section>
  <section><h2>2. Strumenti usati dal sito</h2><div class="legal-table-wrap"><table><thead><tr><th>Strumento</th><th>Fornitore</th><th>Finalità</th><th>Durata</th></tr></thead><tbody><tr><td>Preferenza lingua</td><td>Atelier Doria</td><td>Ricordare la lingua scelta; elemento tecnico</td><td>Secondo la configurazione del browser</td></tr><tr><td>Preferenza mappa</td><td>Atelier Doria</td><td>Ricordare per la sessione l’attivazione volontaria della mappa</td><td>Fine della sessione</td></tr><tr><td>Google Maps</td><td>Google</td><td>Visualizzare la mappa, soltanto dopo un’azione esplicita</td><td>Definita da Google</td></tr></tbody></table></div><p>Il sito non installa direttamente cookie pubblicitari, di profilazione o analytics. I dati tecnici di accesso possono essere registrati dal fornitore di hosting per sicurezza e funzionamento.</p></section>
  <section><h2>3. Google Maps e servizi esterni</h2><p>La mappa è bloccata per impostazione predefinita. Viene caricata solo selezionando il comando dedicato; da quel momento Google può ricevere dati tecnici, incluso l’indirizzo IP, e utilizzare propri cookie o strumenti analoghi. È sempre possibile usare il collegamento esterno alle indicazioni senza incorporare la mappa nella pagina.</p></section>
  <section><h2>4. Gestione delle preferenze</h2><p>La scelta relativa alla mappa dura per la sessione del browser. Chiudendo tutte le schede del sito o cancellando i dati del sito, la preferenza viene rimossa. È inoltre possibile bloccare o cancellare cookie e dati locali dalle impostazioni del browser.</p></section>
  <section><h2>5. Informazioni ulteriori</h2><p>Per il trattamento dei dati personali e l’esercizio dei diritti consulta la <a href="/privacy">Privacy Policy</a>. Per informazioni sui cookie di Google consulta la documentazione del relativo fornitore.</p></section>
</article>
<?php page_end();