<?php require __DIR__ . '/includes/bootstrap.php';
$reviews = array_slice(json_data('recensioni.json'), 0, 3);
$menu_data = json_data('menu.json');
$menu_preview = [];
foreach (array_slice($menu_data['a_la_carte'], 0, 3) as $section) {
    $item = $section['items'][0];
    $separate = !empty($item['name_it']);
    $menu_preview[] = ['category_it'=>$section['category_it'],'category_en'=>$section['category_en'],'name_it'=>$item['name_it']??$item['it'],'name_en'=>$item['name_en']??$item['en'],'description_it'=>$separate?$item['it']:'','description_en'=>$separate?$item['en']:'','price'=>rtrim(rtrim(number_format((float)$item['price'],2,'.',''),'0'),'.').' €'];
}
page_start(); ?>
<section class="hero hero-with-video">
  <div class="hero-media" aria-hidden="true"><img src="<?= asset($photos['featured']['hero_poster']['image']) ?>" alt="" width="1080" height="1350" fetchpriority="high"><video data-hero-video muted loop playsinline preload="none" poster="<?= asset($photos['featured']['hero_poster']['image']) ?>"><?php if ($hero_video_mp4): ?><source src="<?= e($hero_video_mp4) ?>" type="video/mp4"><?php endif; ?><?php if ($hero_video_webm): ?><source src="<?= e($hero_video_webm) ?>" type="video/webm"><?php else: ?><source src="<?= asset('video/hero-atelier-doria.webm') ?>" type="video/webm"><?php endif; ?></video></div>
  <div class="hero-orbit" aria-hidden="true"><span>Radici</span><i></i><span>Presente</span></div>
  <div class="hero-content reveal"><p class="eyebrow">Hostaria · Corso Roma 32, Brindisi</p><h1>La tradizione<br><em>non sta ferma.</em></h1><p>La Puglia di Danilo Doria: sapori onesti, cucina a vista e piatti che ricordano da dove veniamo.</p><div class="actions"><a class="button" href="/prenotazioni">Prenota un tavolo</a><a class="text-link light" href="/menu">Scopri il menu</a></div></div>
  <div class="hero-proof reveal"><strong>8,5</strong><span>su 10 · TheFork<br>22 recensioni</span></div><p class="hero-note">Centro storico<br>Brindisi</p>
</section>
<section class="ticker" aria-label="I valori di Atelier Doria"><div class="ticker-desktop"><span class="ticker-value"><small>01</small>Cucina a vista</span><span class="ticker-value"><small>02</small>Materia locale</span><span class="ticker-value"><small>03</small>Tradizione del Sud</span><span class="ticker-value"><small>04</small>Gesto contemporaneo</span></div><div class="ticker-mobile" aria-hidden="true"><div class="ticker-track"><?php for($i=0;$i<2;$i++): ?><div class="ticker-group"><span>Cucina a vista</span><i></i><span>Materia locale</span><i></i><span>Tradizione del Sud</span><i></i><span>Gesto contemporaneo</span><i></i></div><?php endfor; ?></div></div></section>
<section class="split section story-section"><div class="story-copy reveal"><p class="eyebrow">Danilo Doria</p><h2>Un ritorno che<br><em>diventa cucina</em></h2><p>Dopo l’esperienza a Londra, Danilo torna in Puglia. Non per ripetere la tradizione, ma per rimetterla al centro: fave e cicoria, cozze, lampascioni e pasta diventano un racconto attuale, leggibile, generoso.</p><a class="text-link" href="/chi-siamo">Entra nella storia</a></div><figure class="story-photo reveal"><img src="<?= asset($photos['featured']['home_story']['image']) ?>" alt="<?= e($photos['featured']['home_story']['alt']) ?>" width="1080" height="1920" loading="lazy"><figcaption><span>32</span> Corso Roma · Brindisi</figcaption></figure></section>
<section class="section menu-preview"><div class="section-heading reveal"><p class="eyebrow">Il menu · estate 2026</p><h2>Piatti con una memoria.<br><em>E qualcosa da raccontare.</em></h2></div><div class="dish-editorial">
<?php foreach ($menu_preview as $i=>$item): ?><article class="dish-card reveal"><span>0<?= $i+1 ?></span><p class="eyebrow"><span data-i18n-it="<?= e($item['category_it']) ?>" data-i18n-en="<?= e($item['category_en']) ?>"><?= e($item['category_it']) ?></span></p><h3><span data-i18n-it="<?= e($item['name_it']) ?>" data-i18n-en="<?= e($item['name_en']) ?>"><?= e($item['name_it']) ?></span></h3><?php if($item['description_it']): ?><p><span data-i18n-it="<?= e($item['description_it']) ?>" data-i18n-en="<?= e($item['description_en']) ?>"><?= e($item['description_it']) ?></span></p><?php endif; ?><strong><?= e($item['price']) ?></strong></article><?php endforeach; ?>
</div><div class="menu-preview-footer"><p>Menu pubblicato il <?= e($menu_updated) ?>. Le proposte possono cambiare secondo mercato e stagione.</p><a class="button button-dark" href="/menu">Guarda tutto il menu</a></div></section>
<section class="experience section-dark section"><div class="experience-title reveal"><p class="eyebrow">Non solo cena</p><h2>Dentro la cucina,<br><em>al centro della sala.</em></h2></div><div class="experience-list"><article class="reveal"><span>01</span><div><h3>Cucina a vista</h3><p>Il pass, i gesti e il ritmo del servizio diventano parte della serata.</p></div></article><article class="reveal"><span>02</span><div><h3>Mare e campagna</h3><p>Il porto di Brindisi incontra masserie, orti e ricette familiari.</p></div></article><article class="reveal"><span>03</span><div><h3>Tavola intima</h3><p>Un ambiente curato, raccolto e informale nel centro della città.</p></div></article></div></section>
<figure class="full-bleed-photo"><img src="<?= asset($photos['featured']['home_dish']['image']) ?>" alt="<?= e($photos['featured']['home_dish']['alt']) ?>" width="1080" height="1350" loading="lazy"><figcaption>La tradizione, con uno sguardo contemporaneo.</figcaption></figure>
<section class="section photo-journal"><div class="photo-journal-heading reveal"><p class="eyebrow">Dentro Atelier Doria</p><h2>Una cucina da vivere,<br><em>prima ancora di assaggiarla.</em></h2><p>Interni, cucina a vista, chef, vini e piatti: ogni immagine racconta una parte dell’esperienza.</p><a class="text-link" href="/galleria">Esplora la galleria</a></div><div class="photo-journal-grid"><?php foreach([1,5,16,20,29] as $i): $photo=$photos['gallery'][$i]; ?><figure class="photo-journal-item reveal"><img src="<?= asset($photo['image']) ?>" alt="<?= e($photo['alt']) ?>" width="1080" height="1350" loading="lazy"><figcaption><?= e($photo['caption']) ?></figcaption></figure><?php endforeach; ?></div></section>
<section class="section reviews-home"><div class="reviews-score reveal"><span>Valutazione attuale</span><strong>8,5</strong><p>/10 su TheFork · 22 recensioni</p><a href="<?= e($thefork_url) ?>" target="_blank" rel="noopener">Dati verificati a luglio 2026</a></div><div class="reviews-copy"><p class="eyebrow">Dicono di noi</p><?php foreach($reviews as $r): ?><article class="review-line reveal"><blockquote>“<?= e($r['text']) ?>”</blockquote><a href="<?= e($r['url']) ?>" target="_blank" rel="noopener"><?= e($r['name']) ?> · <?= e($r['source']) ?></a></article><?php endforeach; ?><a class="text-link" href="/recensioni">Tutte le recensioni</a></div></section>
<section class="visit section"><div><p class="eyebrow">Nel cuore di Brindisi</p><h2>Ci vediamo<br>a Corso Roma.</h2><p>Corso Roma, 32 · 72100 Brindisi</p></div><div class="visit-actions"><a class="button button-light" href="/prenotazioni">Prenota ora</a><a class="text-link light" href="https://www.google.com/maps/dir/?api=1&destination=Corso+Roma+32+Brindisi" target="_blank" rel="noopener">Indicazioni stradali</a></div></section>
<?php page_end();
