<?php require __DIR__ . '/includes/bootstrap.php'; $menu=json_data('menu.json'); page_start('Menu 2026 | Atelier Doria Brindisi','Menu aggiornato di Atelier Doria: percorsi degustazione, antipasti pugliesi, primi, pescato, carni e dessert nel centro di Brindisi.'); ?>
<header class="page-hero menu-hero"><p class="eyebrow">Aggiornato il <?= e($menu_updated) ?></p><h1>Il menu</h1><p>Tradizione pugliese, mare Adriatico e cucina contemporanea.</p></header>
<nav class="menu-jump" aria-label="Categorie del menu"><a href="#degustazione">Menu degustazione</a><?php foreach($menu['a_la_carte'] as $i=>$section): ?><a href="#categoria-<?= $i+1 ?>"><span data-i18n-it="<?= e($section['category_it']) ?>" data-i18n-en="<?= e($section['category_en']) ?>"><?= e($section['category_it']) ?></span></a><?php endforeach; ?></nav>
<section class="section menu-layout"><aside class="menu-aside reveal"><figure><img src="<?= asset($photos['featured']['menu']['image']) ?>" alt="<?= e($photos['featured']['menu']['alt']) ?>" width="1080" height="1350" loading="eager" fetchpriority="high"><figcaption>Materia, stagione, memoria.</figcaption></figure><p>La carta segue il mercato e il ritmo della cucina. Chiedi sempre le proposte disponibili al tavolo.</p></aside><div class="menu-list">
<article id="degustazione" class="menu-category reveal"><div class="menu-category-head"><span>01</span><div><h2>Menu degustazione</h2><p>Due percorsi per attraversare la cucina dell’Atelier.</p></div></div><?php foreach($menu['tasting_menus'] as $tasting): ?><div class="menu-item is-signature"><div><h3><?= e($tasting['name']) ?> <small><?= count($tasting['courses']) ?> portate</small></h3><ol><?php foreach($tasting['courses'] as $course): ?><li><span data-i18n-it="<?= e($course['it']) ?>" data-i18n-en="<?= e($course['en']) ?>"><?= e($course['it']) ?></span></li><?php endforeach; ?></ol></div><span><?= number_format((float)$tasting['price'],0,',','.') ?> €</span></div><?php endforeach; ?></article>
<?php foreach($menu['a_la_carte'] as $i=>$section): ?><article id="categoria-<?= $i+1 ?>" class="menu-category reveal"><div class="menu-category-head"><span><?= sprintf('%02d',$i+2) ?></span><div><h2><span data-i18n-it="<?= e($section['category_it']) ?>" data-i18n-en="<?= e($section['category_en']) ?>"><?= e($section['category_it']) ?></span></h2></div></div><?php foreach($section['items'] as $item): $nameIt=$item['name_it']??$item['it']; $nameEn=$item['name_en']??$item['en']; ?><div class="menu-item"><div><h3><span data-i18n-it="<?= e($nameIt) ?>" data-i18n-en="<?= e($nameEn) ?>"><?= e($nameIt) ?></span></h3><?php if(!empty($item['name_it'])&&!empty($item['it'])): ?><p><span data-i18n-it="<?= e($item['it']) ?>" data-i18n-en="<?= e($item['en']) ?>"><?= e($item['it']) ?></span></p><?php endif; ?></div><span><?= number_format((float)$item['price'],0,',','.') ?> €</span></div><?php endforeach; ?></article><?php endforeach; ?>
<p class="notice">Comunica allergie e intolleranze prima dell’ordine. Il personale può fornire il registro allergeni e indicare eventuali variazioni.</p><a class="button" href="/prenotazioni">Prenota un tavolo</a></div></section>
<section class="section"><div class="section-heading reveal"><p class="eyebrow">Dalla cucina</p><h2>Piatti, materia,<br><em>gesti.</em></h2></div><div class="menu-photo-strip"><?php foreach([0,12,17] as $i): $photo=$photos['gallery'][$i]; ?><figure class="reveal"><img src="<?= asset($photo['image']) ?>" alt="<?= e($photo['alt']) ?>" width="1080" height="1350" loading="lazy"><figcaption><?= e($photo['caption']) ?></figcaption></figure><?php endforeach; ?></div></section>
<?php page_end();
