<?php require __DIR__ . '/includes/bootstrap.php';
page_start('Privacy Policy | Atelier Doria','Informativa sul trattamento dei dati personali degli utenti del sito Atelier Doria.'); ?>
<header class="page-hero legal-hero"><div><p class="eyebrow">Trasparenza</p><h1>Privacy Policy</h1><p>Informativa ai sensi degli articoli 13 e 14 del Regolamento (UE) 2016/679.</p></div></header>
<article class="section legal-page">
  <p class="legal-updated"><strong>Ultimo aggiornamento:</strong> 6 agosto 2026. <strong>Bozza soggetta a verifica legale prima della pubblicazione definitiva.</strong></p>
  <section><h2>1. Titolare del trattamento</h2><p>Il titolare del trattamento è <strong>Appia Food S.R.L.S.</strong>, P. IVA 02717510743, con sede legale in Corso Roma 32, 72100 Brindisi (BR), e-mail <a href="mailto:<?= e($contact_email) ?>"><?= e($contact_email) ?></a>.</p></section>
  <section><h2>2. Dati trattati</h2><p>Il sito può trattare dati di navigazione e informazioni fornite volontariamente: nome e cognome, indirizzo e-mail, numero di telefono, data e ora richieste, numero di persone, contenuto dei messaggi e delle note. Le note di prenotazione possono contenere dati relativi ad allergie, intolleranze o altre esigenze alimentari, che possono costituire categorie particolari di dati personali.</p></section>
  <section><h2>3. Finalità e basi giuridiche</h2><ul><li>Rispondere a richieste di contatto e gestire richieste di prenotazione: esecuzione di misure precontrattuali richieste dall’interessato, art. 6, par. 1, lett. b) GDPR.</li><li>Gestire eventuali dati relativi alla salute inseriti volontariamente nelle note: consenso esplicito, art. 9, par. 2, lett. a) GDPR.</li><li>Garantire sicurezza, continuità e prevenzione degli abusi: legittimo interesse del titolare, art. 6, par. 1, lett. f) GDPR.</li><li>Adempiere obblighi di legge o richieste dell’autorità: art. 6, par. 1, lett. c) GDPR.</li></ul><p>I dati non sono utilizzati per marketing o profilazione tramite questo sito.</p></section>
  <section><h2>4. Conferimento dei dati</h2><p>I campi indicati come obbligatori sono necessari per gestire la richiesta. Il mancato conferimento impedisce l’invio. L’inserimento di note, allergie o intolleranze è facoltativo. Non inserire dati sanitari non necessari.</p></section>
  <section><h2>5. Modalità, destinatari e trasferimenti</h2><p>I dati sono trattati con strumenti informatici e misure adeguate al rischio. Possono essere comunicati al personale autorizzato e a fornitori tecnici che operano come responsabili del trattamento, inclusi hosting, posta elettronica e manutenzione. Le prenotazioni inviate tramite WhatsApp sono trattate anche da WhatsApp Ireland Limited secondo le condizioni del relativo servizio. I collegamenti o contenuti di Google, Meta, TheFork e WhatsApp possono comportare trattamenti autonomi e trasferimenti verso Paesi esterni allo Spazio economico europeo secondo le garanzie adottate dai rispettivi fornitori.</p></section>
  <section><h2>6. Conservazione</h2><p>Le richieste di contatto e prenotazione sono conservate per il tempo necessario a gestirle e, salvo contenziosi o obblighi di legge, non oltre 12 mesi dalla chiusura della richiesta. I dati necessari per obblighi amministrativi, fiscali o per la tutela di diritti possono essere conservati per i termini previsti dalla legge. I log tecnici sono conservati per il periodo definito dal fornitore di hosting e limitato alle esigenze di sicurezza.</p></section>
  <section><h2>7. Diritti dell’interessato</h2><p>È possibile chiedere accesso, rettifica, cancellazione, limitazione, portabilità, opposizione e revoca del consenso senza pregiudicare i trattamenti già effettuati. Le richieste vanno inviate a <a href="mailto:<?= e($contact_email) ?>"><?= e($contact_email) ?></a>. È inoltre possibile proporre reclamo al Garante per la protezione dei dati personali.</p></section>
  <section><h2>8. Processi decisionali automatizzati</h2><p>Il sito non svolge processi decisionali automatizzati né profilazione.</p></section>
  <section><h2>9. Aggiornamenti</h2><p>Questa informativa può essere aggiornata in caso di modifiche ai trattamenti o ai servizi. La versione vigente è identificata dalla data riportata in alto.</p></section>
</article>
<?php page_end();